### PR TITLE
I think that is doesn't needed

### PR DESCRIPTION
**Pull request by Dokman**
Edited readme.md

### CODE REVIEW

**Comment by Kittnz** [comment]
I think it is, it's easy for new people to navigate.
Howevery maybe we could remove the extractors. Since there is no release anymore.

**Comment by ghost** [comment]
Can remove extractors and redirect link to forum.

Releases in forum it´s better.

**Comment by Kittnz** [comment]
That's better!

**Comment by Dokman** [comment]
for the moment i close it

**Pull request closed without merging**
