### PR TITLE
Core/Mechanics/Logic/Style

### PR DESCRIPTION
**Pull request by avengerweb**
Core/Mechanics/Logic/Style

### CODE REVIEW

**Comment by Basti420** [comment]
You are a Collaborator, no need to make a pull request anymore. Keep up the nice work.

**Comment by Kittnz** [comment]
Yes added too the team.

**Comment by avengerweb** [comment]
Ok, good.

**Comment by Kittnz** [comment]
End this conversation here and do it on skype or w/e.

**Comment by avengerweb** [comment]
Ended.

**Pull request merged**
