### PR TITLE
Create 2014_04_26_creature.sql

### PR DESCRIPTION
**Pull request by ghost**
Changes SpawnMask, next package will later be checked and tested'll wait comment.. sorry My English..

### CODE REVIEW

**Comment by FALL1N1** [comment]
Instead of replacing the entrie data, use UPDATE `xxxxxx` SET `xxxxxxxxxx` where `xxxxxx` = x;

**Comment by ghost** [comment]
I replaced SpawnMask since MistCore DataBases 5.0.5b many mistakes on this occasion.

**Comment by ghost** [comment]
I am sorry if that is not so I'm just learning...

**Comment by Kittnz** [comment]
@PaulHellCore you have tested this?

**Comment by ghost** [comment]
I just corrected the 4210 all failed to check as much, but not in the database that did not notice, if you check and all is well lay the second pack fixes.

**Comment by caffeine239** [comment]
kittnz add me on skype Caffeine239

**Comment by Kittnz** [comment]
@caffeine239 I think I have you on Skype already.

**Comment by ghost** [comment]
Remove then if you are in doubt.

**Pull request merged**
