### PR TITLE
Closes #47 Thanks to Zhelyazkov

### LINKED ISSUE #47: Guild reputation
with my level 5 test char im gaining guild rep without being in a guild

### PR DESCRIPTION
**Pull request by Basti420**
Closes #47 Thanks to Zhelyazkov

### CODE REVIEW

**Comment by FALL1N1** [comment]
fix the code style and i'll merge it

**Comment by zzhel** [comment]
mah nigga

**Comment by zzhel** [comment]
still not right, your indentation is wrong

**Comment by Basti420** [comment]
i don't get it :D

**Comment by Kittnz** [comment]
@Zhelyazkov as you seen, added too team.

**Pull request closed without merging**
